version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: pweb
      POSTGRES_PASSWORD: pweb
      POSTGRES_DB: education_service_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network 

  service1:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://pweb:pweb@db/education_service_db
      PORT: 8080
      ADDRESS: 0.0.0.0
    ports:
      - "8080:8080"
    networks:
      - app-network 

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
