//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]


#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub surname: String,
    pub group: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub role: UserRole,
    pub additional_contact: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}



#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum UserRole {
    #[sea_orm(string_value = "Student")]
    Student,
    #[sea_orm(string_value = "Teacher")]    
    Teacher,
    #[sea_orm(string_value = "Admin")]
    Admin,
}

impl ActiveModelBehavior for ActiveModel {}
